lmSensors:
  command: sensors

channels:
  file:
    enable: true
    path: ./notifications.out
  notifySend:
    enable: false
    command: notify-send
    expireTime: 10
    hint:
  telegramBot:
    enable: false
    token: "0000000000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    chatId: 000000000

sensors:
  criticalTemperature: 70
  criticalTemperatureUnit: c
  pollingInterval: 10

report:
  format:
    temperatureUnit: —Å
  message:
    title:
      text: "Critical temperature readings [{timestamp}]:"
  repeatTimeout: 1800