lmSensors:
  command: sensors

channels:
  file:
    enable: true
    path: ./notifications.out
  telegramBot:
    enable: false
    token: "0000000000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    chatId: 000000000

sensors:
  criticalTemperature: 70
  pollingInterval: 10

report:
  repeatTimeout: 1800